config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    post 'users/:user_id/friendship', to: 'friendships#add_friend'# , :as 'friendship'
  end
    resources :friendships
  resources :companies do
    resources :company_followers
    # post 'companies/:company_id/company_followers', to: 'company_followers#create'
    # delete 'companies/:company_id/company_followers/:id', to: 'company_followers#destroy'
  end
  resources :jobs

  resources :posts do
    resources :comments do
      resources :comments
    end
  end

  resources :comments do
    resources :comments 
  end
  # post '/auth/login', to: 'authentication#login'
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :image
  has_many :companies, dependent: :destroy
  has_many :friendships
  has_many :users_jobs, dependent: :destroy
  has_many :company_followers, dependent: :destroy
  has_many :friends, through: :friendships, foreign_key: 'friend_id'
  has_many :posts, as: :postable, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



  def full_name
    "#{first_name} #{last_name}".titleize
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def index
		@user = current_user
	end

	def show
		# unless params[:user_id] @user = User.find(current_user.id)
 		@user = User.find(params[:id])
	end

	def destroy
		@user = User.find(current_user.id)
		@user.destroy
		redirect_to root_path
	end



	private

	def user_Params
		params.require.permit(:first_name, :last_name,:country, :city, :qualification, :skill, :birth_date, :user_type)
	end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/index.html.erb
<% if user_signed_in? %> 
 <div style="color: darkcyan;"> Welcome <%= current_user.full_name %> </div> 
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
<% else %>
  <%= button_to "Sign in", new_user_session_path %> 
<% end %>

<div> 
  <h2> user info </h2>
  <p style="font-size: large;"> <%= link_to @user.id, @user %><br>
  <%= link_to @user.full_name, @user %><br> </p>
</div>

<hr>

<div> 
  <h3>companies info</h3>
  <% if @user.user_type == "Company_user" %>

    <% unless @user.companies.nil? %>
      <% companies = @user.companies.all %> 
      <% companies.each do |company| %>
        <%=link_to company.company_name, company_path(company.id) %><br>
      <% end %>
    <% end %> <br> <hr>
    <%= button_to "Create Company", new_company_path, method: :get  %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1> Show User</h1>
<li>
	<% if @user.image.persisted? %>
		profile photo <%= image_tag @user.image,width: 80 %> 
	<% end %>
</li>
<li> user id: <%= @user.id %> </li>
<li> full name: <%= @user.full_name %> </li>
<li><%= link_to "Destroy", users_path(@user), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>

<li><%#  button_to 'add_friend', create_inverse %></li>
<%# link_to "add_friend", new_user_friendship_path(@user.id) %>
<%# byebug %>
<% unless @user.id == current_user.id %>
	<% if current_user.id %>
		<%= button_to 'Add Friend', friendships_path(user_id: current_user.id,friendship: {friend_id: params[:id], user_id: current_user.id, requester_id: current_user.id}), method: :post%>
	<% end %>
<% end %>