config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    post 'users/:user_id/friendship', to: 'friendships#add_friend'# , :as 'friendship'
  end
    resources :friendships
  resources :companies do
    resources :company_followers
    # post 'companies/:company_id/company_followers', to: 'company_followers#create'
    # delete 'companies/:company_id/company_followers/:id', to: 'company_followers#destroy'
  end
  resources :jobs

  resources :posts do
    resources :comments do
      resources :comments
    end
  end

  resources :comments do
    resources :comments 
  end
  # post '/auth/login', to: 'authentication#login'
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'

  scope :frend, -> { where(status: true) }
  scope :requests, ->{ where(status: false) }
  

  private

  # def create_inverse
  #   self.class.create(user_id: self.friend.id, friend_id: self.user.id, status: 'pending')
  # end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!
  def index
  	# byebug 
  	@friendship = Friendship.all.frend
  	@request = Friendship.all.requests
  end

  def show

  end

	def new 

	end

	def create
		@user = current_user.friendships.new(user_id: current_user.id,friend_id: params[:friendship][:friend_id], requester_id: params[:friendship][:requester_id])
		# @friend = Friendship.new(user_id: params[:friendship][:friend_id],friend_id: params[:friendship][:user_id], requester_id: params[:friendship][:requester_id])
		@user.save #&& @friend.save
		flash[:notice] = "Added friend."
		redirect_to friendships_path
		
		# redirect_to @friend
	end

	def update
		# byebug
		friend = Friendship.find_by(id: params[:id])
		friend.update(status: true,user_id: current_user.id)
		# @user.status = Friendship.friends
		redirect_to friendships_path
	end

	def destroy 
		# byebug
		friend = Friendship.find_by(id: params[:id])
		friend.destroy
		redirect_to friendships_path
	end

	# def request

	# end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_friend.html.erb
<% @users = User.all %>
<% @users.each do |user| %>
<%# byebug %>
	<% if user.id != current_user.id %>
		<%=link_to user.full_name, user_path(user) %> <br>
	<% end %>
<% end %>

app/views/friendships/index.html.erb
current user id : <%= current_user.id %> <hr>
<p>  <%= button_to "Add more Friends", new_friendship_path,method: :get %> </p>
<h2> friends </h2> 
 <% @friendship.each do |friend| %> <br>
 	<% if current_user.id == friend.requester_id  %>
		<% user = User.find_by(id: friend.friend_id) %> 
		<%= link_to user.full_name, user_path(user.id) %> 
		<%= button_to "delete friendship", friendship_path(friend.id),method: :delete %> <br>
	<% elsif current_user.id == friend.friend_id %>
		<% user = User.find_by(id: friend.friend_id) %> 
		<%= link_to user.full_name, user_path(user.id) %> 
		<%= button_to "delete friendship", friendship_path(friend.id),method: :delete %> <br>
	<% end %>
<% end %> <br> <hr>

<h2> sended requests </h2>
<% @request.each do |request| %> <br>
<% byebug %>
	<% user = User.find_by(id: request.friend_id) %> 
	<%= link_to user.full_name, user_path(user.id) %>
	<%= button_to "delete request", friendship_path(request.id),method: :delete %> <br>
<% end %> <br> <hr>

<h2> recived requests </h2>
<% @friends = Friendship.where(friend_id: current_user.id) %>
<% @friends.each do |accept| %>
	<% if accept.status == false %>
		<% user = User.find_by(id: accept.requester_id) %>
		<%= user.full_name %>
		<%= button_to "accept", friendship_path(accept.id),method: :put %>
	<% end %>
<% end %> <br>

app/views/friendships/new.html.erb
<h1>new friendship </h1>
 <%= render "friend", user: @user %>
 <%# byebug %>
  