config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    post 'users/:user_id/friendship', to: 'friendships#add_friend'# , :as 'friendship'
  end
    resources :friendships
  resources :companies do
    resources :company_followers
    # post 'companies/:company_id/company_followers', to: 'company_followers#create'
    # delete 'companies/:company_id/company_followers/:id', to: 'company_followers#destroy'
  end
  resources :jobs

  resources :posts do
    resources :comments do
      resources :comments
    end
  end

  resources :comments do
    resources :comments 
  end
  # post '/auth/login', to: 'authentication#login'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy

end

app/models/company.rb
class Company < ApplicationRecord
	belongs_to :user 
	has_many :jobs, dependent: :destroy
	has_many :company_followers, dependent: :destroy
	has_many :posts, as: :postable, dependent: :destroy
	validates :company_name, presence: true
end

app/models/company_follower.rb
class CompanyFollower < ApplicationRecord
  belongs_to :company
  belongs_to :user
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'

  scope :frend, -> { where(status: true) }
  scope :requests, ->{ where(status: false) }
  

  private

  # def create_inverse
  #   self.class.create(user_id: self.friend.id, friend_id: self.user.id, status: 'pending')
  # end

end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company
  has_many :users_jobs, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :postable,polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy
  has_one_attached :image
  # belongs_to :company, optional: true
  # belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :image
  has_many :companies, dependent: :destroy
  has_many :friendships
  has_many :users_jobs, dependent: :destroy
  has_many :company_followers, dependent: :destroy
  has_many :friends, through: :friendships, foreign_key: 'friend_id'
  has_many :posts, as: :postable, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



  def full_name
    "#{first_name} #{last_name}".titleize
  end


end

app/models/users_job.rb
class UsersJob < ApplicationRecord
  belongs_to :user
  belongs_to :job
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected
	
	def configure_permitted_parameters
	# byebug
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :gender, :user_type, :qualification, :skill, :birth_date, :country, :city,:image]) 
	end
	
  def name
    "#{first_name} #{middle_name} #{last_name}".titleize
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_commentable
	def show
		# byebug
		@comment =  if params[:comment_id]
	  									Comment.find_by(id: params[:comment_id])
	  								else
	  									Comment.find_by(id: params[:id])
	  								end
		byebug
		user = User.find_by(id: @comment.user_id)
		@comment.user_name = user.full_name
	end

	def new
		byebug
	  @comment = @commentable.comments.new
	end

	def create
		@commentable = if params[:comment_id]
	  									Comment.find_by(id: params[:comment_id])
	  								else
	  									Post.find_by(id: params[:post_id])
	  								end
	  @comment = @commentable.comments.new(comment_params)									
	  @comment.user_id = current_user.id
	  # @comment.user_name = current_user.full_name
	  @comment.save
	  byebug
	  if  params[:comment_id] == nil
	  	redirect_to post_path(params[:post_id])
		else
	  	redirect_to post_path(params[:comment_id])
	  end
	end

	private

	def comment_params
		params.require(:comment).permit(:content)
	end

	def set_commentable
		# byebug
			@commentable = 
		  								if params[:post_id]
		  									Comment.find_by(id: params[:post_id])
		  								elsif params[:comment_id]
		  									Comment.find_by(id: params[:comment_id])
		  								else
		  									Comment.find_by(id: params[:id])
		  								end
	end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
	def index
		byebug
		@companies = Company.all
	end

	def show
		@company = Company.find_by(id: params[:id])
	end

	def new
		@company = current_user.companies.new
	end

	def create
		byebug
		@company = current_user.companies.new(company_params)
		if @company.save
			redirect_to root_path
		else
			render :new, status: :unprocessable_entity
		end
	end
  
  def destroy
  	@company = Company.find_by(id: params[:id])
  	if @company.destroy
  		redirect_to root_path
  	else
  		render :show, status: :see_other
  	end
  end

	private
	def company_params
		params.require(:company).permit(:company_name,:company_size,:company_type,:specialities,:founded_in,:website,:address,:about,:user_id)
	end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!
	def index
		@jobs = Job.all
	end

	def show
		@job = Job.find_by(id: params[:id])
	end

	def new
		@job = Job.new
	end

	def create
		@company = Company.find_by(id: params[:company_id])
		@job = Job.new(job_params)
		if @job.save
			redirect_to company_path(params[:company_id])
		else
			render :new, status: :unprocessable_entity
		end
	end
	


	private

	def job_params
		params.require(:job).permit(:title,:description,:salary,:position)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
	before_action :set_commentable

  def index 
  	# byebug
  	@posts = Post.all 
  	# @posts.user = current_user
  end

  def show
  	# byebug
  	@post =  Post.find(params[:id])
  end

  def new
  	
  end

	def create
		post = current_user.posts.new(post_params)
		post.user_name = current_user.full_name
			# byebug
		if post.save
			redirect_to post
		else
			render :new, status: :unprocessable_entity
		end
	end

	def edit
		@post = current_user.posts.new
	end

	def update
	 @post = current_user.posts.new(post_params)
	 if @post.update
	 	redirect_to @post
	 else
	 	render :edit, status: :unprocessable_entity
	 end
	end

	def destroy
		byebug
		@post = Post.find_by(id: params[:id])
		@post.destroy
		redirect_to post_path
	end

	private

	def set_commentable
		# byebug	
		@commentable = Post.find_by(id: params[:id])
	end


	def post_params
		params.require(:post).permit(:article, :image)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def index
		@user = current_user
	end

	def show
		# unless params[:user_id] @user = User.find(current_user.id)
 		@user = User.find(params[:id])
	end

	def destroy
		@user = User.find(current_user.id)
		@user.destroy
		redirect_to root_path
	end



	private

	def user_Params
		params.require.permit(:first_name, :last_name,:country, :city, :qualification, :skill, :birth_date, :user_type)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/company_followers_helper.rb
module CompanyFollowersHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/companies/_form.html.erb
<%= form_with model: company do |form| %>
  <div>
    <%= form.label :company_name %>
    <%= form.text_field :company_name %> <br> <br>
    <%# company.errors.full_messages_for(:company_name).each do | message | %>
       <!-- <div style="color: red;">< %=  message  %></div> -->
    <%# end %>

    <%= form.label :company_type %>
       <%= form.text_field :company_type %><br> <br>

    <%= form.label :specialities %>
        <%= form.text_area :specialities %><br> <br>

    <%= form.label :founded_in %>
        <%= form.select :founded_in, Date.today.year-50 ... Date.today.year %><br> <br>

    <%= form.label :website %>
        <%= form.text_field :website %> <br> <br>

    <%= form.label :number_of_employee %>
        <%= form.number_field :company_size %> <br> <br>

    <%= form.label :address %>
      <%= form.text_field :address %> <br> <br>

    <%= form.label :about %>
      <%= form.text_area :about %> <br> <br>
 </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/index.html.erb
<!-- < % if user_signed_in? %>  -->

 <% @companies.each do |company| %>
 <!-- < % byebug %> -->
  <%= link_to company.company_name , company %><br>
  <% end %>

  <%= link_to "create new company", new_company_path %>
<!-- < % end %> -->

app/views/companies/new.html.erb
<div align="center">
<h1>New Company</h1>
<%= render "companies/form", company: @company %> 
</div>

app/views/companies/show.html.erb
<h1>company details</h1>


<p style="font-size: large;"> <%= "Name : #{@company.company_name}" %> </p>
<p style="font-size: large;"> <%= "Company Type : #{@company.company_type}" %> </p>
<p style="font-size: large;"> <%= "Specialitie : #{@company.specialities}" %> </p>
<p style="font-size: large;"> <%= "Founded in : #{@company.founded_in}" %> </p>
<p style="font-size: large;"> <%= "Website : #{@company.website}" %> </p>
<p style="font-size: large;"> <%= "Address : #{@company.address}" %> </p>
<p style="font-size: large;"> <%= "Adout : #{@company.about}" %> </p>


<% @follower = CompanyFollower.all.find_by(user_id: current_user.id) %>
<% if @company.user_id == current_user.id %>
<%# byebug %>
	 <%#= button_to "Edit", [:edit, @company], method: :get %> <br>
	<p> <%= button_to "Destroy", company_path(@company),method: :delete %></p>
	
 	<% byebug %>
	<p> <%= button_to "add New", new_job_path,method: :get %></p>
<% elsif CompanyFollower.all.where(user_id: current_user.id).present? %>
	<p> <%= button_to "Unfollow", company_company_follower_path(@company.id,@follower ),method: :delete %></p>
<% else %>
	<p> <%= button_to "Follow", company_company_followers_path(@company.id),method: :post %></p>
<% end %>

<% @jobs =  @company.jobs.all %>
<% @jobs.each do |job| %>
	<%= link_to job.title,job_path(job.id) %>
<% end %>

app/views/posts/_form.html.erb
<%= form_with model: post do |form| %>
  <div>
    <%= form.label :article %><br>
    <%= form.text_area :article%>

    <% post.errors.full_messages_for(:article).each do | message | %>
       <div style="color: red;"><%=  message  %></div>
    <% end %>
  </div>

  <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div align="center">
<h1>EDIT POST</h1>
<%= render "form", post: @post %>
</div>

app/views/posts/index.html.erb
<h1> index post</h1>
<ul>
<% @posts.each do |post| %>
	<li> <%= link_to  post.user_name, users_path %> </li>
	<li> <%= link_to post.article, post %> </li>

	<li>
		<% if post.image.attached? %>
			<%=link_to (image_tag post.image,width: 400),post %> 
		<% end %>
	</li>


<% end %>
</ul>

<div> <%= button_to "new Post", new_post_path, method: :get %> </div>

app/views/posts/new.html.erb
<div align="center">
<h1>New Post</h1>
<%= render "form", post: @post%> 
</div>

app/views/posts/show.html.erb
<h1>show post</h1>

<p style="font-size: large;"> <%= @post.article %> </p>
<p>
<% if @post.image.attached? %>
	<%= image_tag @post.image,width: 400 %> 
<% end %>
</p>
<% if @post.postable_id == current_user.id %>
<%# byebug %>
	 <%= button_to "Edit", [:edit, @post], method: :get %> <br>
	<p> <%= button_to "Destroy", post_path(@post),method: :delete %></p>
<% end %>

<p>
	<%= render  @commentable.comments%>
</p>

<p>
	<%= render 'comments/form' %>
</p> 