config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    post 'users/:user_id/friendship', to: 'friendships#add_friend'# , :as 'friendship'
  end
    resources :friendships
  resources :companies do
    resources :company_followers
    # post 'companies/:company_id/company_followers', to: 'company_followers#create'
    # delete 'companies/:company_id/company_followers/:id', to: 'company_followers#destroy'
  end
  resources :jobs

  resources :posts do
    resources :comments do
      resources :comments
    end
  end

  resources :comments do
    resources :comments 
  end
  # post '/auth/login', to: 'authentication#login'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy

end

app/models/company.rb
class Company < ApplicationRecord
	belongs_to :user 
	has_many :jobs, dependent: :destroy
	has_many :company_followers, dependent: :destroy
	has_many :posts, as: :postable, dependent: :destroy
	validates :company_name, presence: true
end

app/models/company_follower.rb
class CompanyFollower < ApplicationRecord
  belongs_to :company
  belongs_to :user
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'

  scope :frend, -> { where(status: true) }
  scope :requests, ->{ where(status: false) }
  

  private

  # def create_inverse
  #   self.class.create(user_id: self.friend.id, friend_id: self.user.id, status: 'pending')
  # end

end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company
  has_many :users_jobs, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :postable,polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy
  has_one_attached :image
  # belongs_to :company, optional: true
  # belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :image
  has_many :companies, dependent: :destroy
  has_many :friendships
  has_many :users_jobs, dependent: :destroy
  has_many :company_followers, dependent: :destroy
  has_many :friends, through: :friendships, foreign_key: 'friend_id'
  has_many :posts, as: :postable, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



  def full_name
    "#{first_name} #{last_name}".titleize
  end


end

app/models/users_job.rb
class UsersJob < ApplicationRecord
  belongs_to :user
  belongs_to :job
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_commentable
	def show
		# byebug
		@comment =  if params[:comment_id]
	  									Comment.find_by(id: params[:comment_id])
	  								else
	  									Comment.find_by(id: params[:id])
	  								end
		byebug
		user = User.find_by(id: @comment.user_id)
		@comment.user_name = user.full_name
	end

	def new
		byebug
	  @comment = @commentable.comments.new
	end

	def create
		@commentable = if params[:comment_id]
	  									Comment.find_by(id: params[:comment_id])
	  								else
	  									Post.find_by(id: params[:post_id])
	  								end
	  @comment = @commentable.comments.new(comment_params)									
	  @comment.user_id = current_user.id
	  # @comment.user_name = current_user.full_name
	  @comment.save
	  byebug
	  if  params[:comment_id] == nil
	  	redirect_to post_path(params[:post_id])
		else
	  	redirect_to post_path(params[:comment_id])
	  end
	end

	private

	def comment_params
		params.require(:comment).permit(:content)
	end

	def set_commentable
		# byebug
			@commentable = 
		  								if params[:post_id]
		  									Comment.find_by(id: params[:post_id])
		  								elsif params[:comment_id]
		  									Comment.find_by(id: params[:comment_id])
		  								else
		  									Comment.find_by(id: params[:id])
		  								end
	end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
	def index
		byebug
		@companies = Company.all
	end

	def show
		@company = Company.find_by(id: params[:id])
	end

	def new
		@company = current_user.companies.new
	end

	def create
		byebug
		@company = current_user.companies.new(company_params)
		if @company.save
			redirect_to root_path
		else
			render :new, status: :unprocessable_entity
		end
	end
  
  def destroy
  	@company = Company.find_by(id: params[:id])
  	if @company.destroy
  		redirect_to root_path
  	else
  		render :show, status: :see_other
  	end
  end

	private
	def company_params
		params.require(:company).permit(:company_name,:company_size,:company_type,:specialities,:founded_in,:website,:address,:about,:user_id)
	end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!
	def index
		@jobs = Job.all
	end

	def show
		@job = Job.find_by(id: params[:id])
	end

	def new
		@job = Job.new
	end

	def create
		@company = Company.find_by(id: params[:company_id])
		@job = Job.new(job_params)
		if @job.save
			redirect_to company_path(params[:company_id])
		else
			render :new, status: :unprocessable_entity
		end
	end
	


	private

	def job_params
		params.require(:job).permit(:title,:description,:salary,:position)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
	before_action :set_commentable

  def index 
  	# byebug
  	@posts = Post.all 
  	# @posts.user = current_user
  end

  def show
  	# byebug
  	@post =  Post.find(params[:id])
  end

  def new
  	
  end

	def create
		post = current_user.posts.new(post_params)
		post.user_name = current_user.full_name
			# byebug
		if post.save
			redirect_to post
		else
			render :new, status: :unprocessable_entity
		end
	end

	def edit
		@post = current_user.posts.new
	end

	def update
	 @post = current_user.posts.new(post_params)
	 if @post.update
	 	redirect_to @post
	 else
	 	render :edit, status: :unprocessable_entity
	 end
	end

	def destroy
		byebug
		@post = Post.find_by(id: params[:id])
		@post.destroy
		redirect_to post_path
	end

	private

	def set_commentable
		# byebug	
		@commentable = Post.find_by(id: params[:id])
	end


	def post_params
		params.require(:post).permit(:article, :image)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def index
		@user = current_user
	end

	def show
		# unless params[:user_id] @user = User.find(current_user.id)
 		@user = User.find(params[:id])
	end

	def destroy
		@user = User.find(current_user.id)
		@user.destroy
		redirect_to root_path
	end



	private

	def user_Params
		params.require.permit(:first_name, :last_name,:country, :city, :qualification, :skill, :birth_date, :user_type)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
y<!DOCTYPE html>
<html>
  <head>
    <title>Linkdin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_tag %> <!-- it is the salution of java script errors -->
    <!-- < %= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> -->
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light
        navbar-inverse navbar-fixed-top mb-4" style="display: inline-flex; padding: 10px;">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <% if current_user %>
            <%= link_to posts_path, class: "navbar-brand" do %>
              <img src="assets/home-button.png" class="avatar float-left" alt='Home' height="40px" width="40px" /> 
            <% end %>
          <% end %>
        </li>
      </ul>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <% if current_user %>
          <%# byebug %>
            <%= link_to friendships_path, class: 'nav-link' do %>
              <img src="assets/network-icon.png" class="avatar float-left" alt='Connection' height="40px" width="40px" /> 
            <% end %>
          <% end %>
        </li>
      </ul>
      
    </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <% if current_user %>
            <%= link_to jobs_path, class: 'nav-link' do %>
              <img src="assets/job_search.png" class="avatar float-left" alt='job Search' height="40px" width="40px" /> 
            <% end %>
          <% end %>
        </li>
      </ul>
      
    </div>
  </nav>

    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p>


    <%= yield %>
  </body>
</html>